export const SITE_NAME = "MyStudyAlly";
export const SITE_TAGLINE = "Curriculum-matched tutoring, done properly";
export const SITE_URL = "https://mystudyally.com";

// Canonical inquiry response-time SLA. The design files disagreed (some said
// "within 24 hours", the inquiry form said "within 2 hours" with an office-hours
// caveat) — 24 hours was chosen as the value every page should render from here,
// never hardcode a response time elsewhere.
export const SLA_RESPONSE_TIME = "within 24 hours";

// SABIS stays out of the index until its subject list is verified against the
// real tutor pool (implementation plan, Part 3 item 4). Remove the slug here
// once that's confirmed.
export const NOINDEX_CURRICULA: string[] = ["sabis"];

// TODO(legal): replace with the registered company name + number once the
// entity is formed. The plan lists this as a launch blocker — /privacy/ and
// /terms/ render these verbatim, and UK GDPR expects the data controller to be
// identifiable before the form collects anything.
export const LEGAL_ENTITY_NAME = "MyStudyAlly";
export const LEGAL_POLICY_LAST_UPDATED = "15 August 2026";

export const CONTACT_EMAIL = "info@mystudyally.com";
export const CONTACT_WHATSAPP_DISPLAY = "+44 7868 197793";
export const CONTACT_WHATSAPP_LINK = "https://wa.me/447868197793";
// Structured so the footer, the /contact/ page and the JSON-LD PostalAddress
// all derive from one definition — a mismatch between the visible address and
// the marked-up one is exactly what breaks a business listing.
export const CONTACT_ADDRESS_PARTS = {
  street: "7 Leamington Gardens",
  locality: "Ilford",
  postalCode: "IG3 9TX",
  country: "United Kingdom",
  countryCode: "GB",
} as const;

export const CONTACT_ADDRESS = `${CONTACT_ADDRESS_PARTS.street}, ${CONTACT_ADDRESS_PARTS.locality} ${CONTACT_ADDRESS_PARTS.postalCode}, ${CONTACT_ADDRESS_PARTS.country}`;

// Social/OG share card. Generated by scripts/gen-brand-assets.mjs.
export const OG_IMAGE_PATH = "/og.png";

export const SOCIAL_LINKS = {
  whatsapp: CONTACT_WHATSAPP_LINK,
  instagram: "https://www.instagram.com/mystudyally",
  linkedin: "https://www.linkedin.com/company/my-study-ally/",
  email: `mailto:${CONTACT_EMAIL}`,
  trustpilot: "https://www.trustpilot.com/review/mystudyally.com",
};

// Cloudflare Worker form endpoint + Turnstile site key are public by design
// (see implementation plan Part 0, secrets map). Set in .env.local to override.
// Defaults to the live workers.dev URL — swap to forms.mystudyally.com once
// that custom domain route is added to the Worker.
export const FORM_ENDPOINT =
  process.env.NEXT_PUBLIC_FORM_ENDPOINT ??
  "https://mystudyally-forms-worker.mystudyally1.workers.dev/";
export const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? "";

// ---------------------------------------------------------------- SEO -------

// Homepage/meta description. Deliberately longer and more specific than
// SITE_TAGLINE: the tagline is a brand line, this is the ~155-character snippet
// Google renders under the result, so it names the curricula families search
// for and the two differentiators (curriculum-matched, recorded).
export const SITE_DESCRIPTION =
  "Online 1-to-1 tutoring matched to your exact exam board — IGCSE, GCSE, A Levels, IB, IELTS and SAT. Every session recorded, and a free trial with no card required.";

// Used by the EducationalOrganization JSON-LD. Founded date is stated on
// /about/ ("Founded in 2026"); keep the two in step.
export const FOUNDING_YEAR = "2026";

// The markets named in the homepage proof strip. Mirrored into `areaServed` so
// the entity is associated with these regions rather than a vague "Worldwide".
export const SERVICE_AREA_COUNTRIES = [
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Canada",
  "Pakistan",
] as const;

// Subject/topic entities the organisation is an authority on. `knowsAbout` is
// how a service entity declares its topical scope to search engines.
export const KNOWS_ABOUT = [
  "IGCSE tutoring",
  "GCSE tutoring",
  "A Level tutoring",
  "IB Diploma tutoring",
  "HKDSE tutoring",
  "American curriculum tutoring",
  "Canadian curriculum tutoring",
  "IELTS preparation",
  "SAT preparation",
  "Online private tutoring",
] as const;

// Search Console / Bing ownership tokens. Left blank until the properties are
// verified — an empty string emits no tag, a wrong one is worse than none.
export const GOOGLE_SITE_VERIFICATION = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ?? "";
export const BING_SITE_VERIFICATION = process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION ?? "";

// Support hours. Rendered on /contact/ and marked up in the organisation's
// ContactPoint and the /contact/ page schema — previously three independent
// copies of the same fact. Hours that disagree between the visible page and the
// markup are exactly the inconsistency that keeps a business panel from
// resolving, so they derive from here.
export const SUPPORT_HOURS = {
  opens: "09:00",
  closes: "18:00",
  /** Both teams keep the same local window; the display names both zones. */
  display: "09:00–18:00 GST · 09:00–18:00 GMT",
  days: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
} as const;
