export const SITE_NAME = "MyStudyAlly";
export const SITE_TAGLINE = "Curriculum-matched tutoring, done properly";
export const SITE_URL = "https://mystudyally.com";

// Canonical inquiry response-time SLA. The design files disagreed (some said
// "within 24 hours", the inquiry form said "within 2 hours" with an office-hours
// caveat) — 24 hours was chosen as the value every page should render from here,
// never hardcode a response time elsewhere.
export const SLA_RESPONSE_TIME = "within 24 hours";

// SABIS stays out of the index until its subject list is verified against the
// real tutor pool (implementation plan, Part 3 item 4). Remove the slug here
// once that's confirmed.
export const NOINDEX_CURRICULA: string[] = ["sabis"];

// TODO(legal): replace with the registered company name + number once the
// entity is formed. The plan lists this as a launch blocker — /privacy/ and
// /terms/ render these verbatim, and UK GDPR expects the data controller to be
// identifiable before the form collects anything.
export const LEGAL_ENTITY_NAME = "MyStudyAlly";
export const LEGAL_POLICY_LAST_UPDATED = "15 August 2026";

export const CONTACT_EMAIL = "info@mystudyally.com";
export const CONTACT_WHATSAPP_DISPLAY = "+44 7868 197793";
export const CONTACT_WHATSAPP_LINK = "https://wa.me/447868197793";
// Structured so the footer, the /contact/ page and the JSON-LD PostalAddress
// all derive from one definition — a mismatch between the visible address and
// the marked-up one is exactly what breaks a business listing.
export const CONTACT_ADDRESS_PARTS = {
  street: "7 Leamington Gardens",
  locality: "Ilford",
  postalCode: "IG3 9TX",
  country: "United Kingdom",
  countryCode: "GB",
} as const;

export const CONTACT_ADDRESS = `${CONTACT_ADDRESS_PARTS.street}, ${CONTACT_ADDRESS_PARTS.locality} ${CONTACT_ADDRESS_PARTS.postalCode}, ${CONTACT_ADDRESS_PARTS.country}`;

// Social/OG share card. Generated by scripts/gen-brand-assets.mjs.
export const OG_IMAGE_PATH = "/og.png";

export const SOCIAL_LINKS = {
  whatsapp: CONTACT_WHATSAPP_LINK,
  instagram: "https://www.instagram.com/mystudyally",
  email: `mailto:${CONTACT_EMAIL}`,
  trustpilot: "https://www.trustpilot.com/review/mystudyally.com",
};

// Cloudflare Worker form endpoint + Turnstile site key are public by design
// (see implementation plan Part 0, secrets map). Set in .env.local to override.
// Defaults to the live workers.dev URL — swap to forms.mystudyally.com once
// that custom domain route is added to the Worker.
export const FORM_ENDPOINT =
  process.env.NEXT_PUBLIC_FORM_ENDPOINT ??
  "https://mystudyally-forms-worker.mystudyally1.workers.dev/";
export const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? "";
